### ISSUE TITLE
ssh:// urls are not understood

### ISSUE THREAD

**Issue by docwhat** [tpope/vim-rhubarb#15]
Using an enterprise github server, I cloned my repositories using `ssh://git@github.example.com/myorg/myrepo.git`.

I expected that:
- The `omnifunc` to be available in commits for things like `Closes #<C-x><C-o>`; instead I got a message that `omnifunc` wasn't set.
- `:Gbrowse` should open the repository url; instead I got "origin is not supported"

I worked around this by using `git remote set-url`:

```
$ git remote set-url origin git@github.example.com:/myorg/myrepo.git
```

I suspect that remotes that explicitly using `ssh://` are not supported. I don't know if this is a rhubarb or fugitive problem.

**Comment by SevereOverfl0w** [comment]
I believe I just fixed this in #16
