### ISSUE TITLE
Add support for Gitlab

### ISSUE THREAD

**Issue by jamietanna** [tpope/vim-rhubarb#17]
It'd be great to get the same functionality for Gitlab - as I use it in both a personal and enterprise environment, as I've recently discovered this and found it really useful.

Would this be best as a PR, or as a separate plugin?

**Comment by tpope** [comment]
https://github.com/shumphrey/fugitive-gitlab.vim

**Comment by jamietanna** [comment]
Sorry, I should have been more specific. I am mainly looking for the ability to have omnicomplete for issue numbers, etc.

**Comment by tpope** [comment]
Unless there is a really strong reason to do otherwise (e.g., near identical apis between the two services), I think rhubarb.vim should stick to GitHub.
