### ISSUE TITLE
:Gbrowse opens wrong URL

### ISSUE THREAD

**Issue by matyus** [tpope/vim-rhubarb#21]
Not sure if you've ever come across this, but whenever I use `:Gbrowse` it opens a url to this repo (`https://github.com/tpope/vim-rhubarb`) instead of the lines I have visually selected in my repo. 

(This worked for my in the past, I occasionally pull master on bundle to update it, I'm not sure when it stopped working.)

**Comment by tpope** [comment]
That's supposed to be a hint that you don't have rhubarb.vim installed. :)

**Comment by matyus** [comment]
@tpope haha omg I'm an idiot, it totally works now. thank you!

**Comment by vergenzt** [comment]
@tpope could that hint be mentioned in the Readme? 🙂 

I too was rather perplexed as to why I was being redirected here instead of to my repo, and it was not at all clear to me that I needed to install this.
