### ISSUE TITLE
omnicomplete not working in repo with no issues

### ISSUE THREAD

**Issue by petobens** [tpope/vim-rhubarb#23]
Steps to reproduce:
i) Create a `foo.gitcommit` in a repo without issues
ii) run `:setlocal omnifunc=rhubarb#omnifunc`
iii) type `Fix` and press `<C-X><C-O`

I get the following error messages:
```
Error detected while processing function rhubarb#omnifunc:
line   20:
E121: Undefined variable: message
Error detected while processing function rhubarb#omnifunc:
line   20:
E116: Invalid arguments for function <SNR>209_throw
```

Is this expected? Thanks!

**Comment by tpope** [comment]
I just fixed the error message. Depending on what error you actually get now a second fix might be in order.

**Comment by petobens** [comment]
Thank you! Now I'm getting the following error:
```
Error detected while processing function rhubarb#omnifunc:
line   27:
rhubarb: Validation Failed
```

**Comment by tpope** [comment]
Based on https://developer.github.com/v3/ that might mean something is wrong with the search query we are sending. You can play with calling `rhubarb#repo_search('issues', 'state:open query terms')` directly if you want to try to debug further.

**Comment by petobens** [comment]
Mmm i'm seeing the following:

```
{'documentation_url': 'https://developer.github.com/v3/search/', 'errors': [{'code': 'invalid', 'field': 'q', 'message': 'The listed users and repositories cannot be searched either because the resources do not e
xist or you do not have permission to view them.', 'resource': 'Search'}], 'message': 'Validation Failed'}
```
The repo is part of the organization I work for. The strange thing is that I can see/modify/create it issues in it withot problems.

**Comment by tpope** [comment]
Did you authenticate as explained in the README?

**Comment by petobens** [comment]
Totally missed it. Sorry for that. Closing. Thanks for the help!
