### ISSUE TITLE
 origin is not a GitHub repository

### ISSUE THREAD

**Issue by teto** [tpope/vim-rhubarb#24]
Doing ^X ^O while redacting commit message on a repo with 2 remotes "upstream" and "gh" (but no "origin"), I get:
```
Erreur détectée en traitant function rhubarb#omnifunc :                                                                                 
ligne   27 :
rhubarb: origin is not a GitHub repository
```
I wonder if it comes from https://github.com/tpope/vim-rhubarb/blob/master/autoload/rhubarb.vim#L48 and if there is an easy way to get the appropriate remote (at least a valid one).

**Comment by mathstuf** [comment]
Hmm. That line also doesn't support `insteadOf` configuration. It should run `git remote get-url $remote` instead of querying the configuration value.

**Comment by holygeek** [comment]
I have similar problem.

I use more than one github accounts and make use of git's `url.replacement.insteadOf` configs to tell ssh which keys to use when connecting to github.com by associating `replacement` with the right key. In my global git config file `~/.gitconfig` I have entries like the following:

```ini
[url "git@github.com-foo:bar"]
	insteadOf = git@github.com:bar

[url "git@github.com-frob:nitz"]
	insteadOf = git@github.com:nitz
```

And in my `~/.ssh/config`:

```
host github.com-foo
    hostname github.com
    identityfile ~/.ssh/foo

host github.com-frob
    hostname github.com
    identityfile ~/.ssh/frob
```

At the moment I make it work with my setup like this:

```diff
diff --git autoload/rhubarb.vim autoload/rhubarb.vim
index 3e7e34f..6e521b5 100644
--- autoload/rhubarb.vim
+++ autoload/rhubarb.vim
@@ -24,13 +24,14 @@ function! s:shellesc(arg) abort
 endfunction
 
 function! rhubarb#homepage_for_url(url) abort
-  let domain_pattern = 'github\.com'
+  let domain_pattern = 'github\.com\(-[a-z]\+\)\?'
   let domains = get(g:, 'github_enterprise_urls', get(g:, 'fugitive_github_domains', []))
   call map(copy(domains), 'substitute(v:val, "/$", "", "")')
   for domain in domains
     let domain_pattern .= '\|' . escape(split(domain, '://')[-1], '.')
   endfor
   let base = matchstr(a:url, '^\%(https\=://\|git://\|git@\|ssh://git@\)\=\zs\('.domain_pattern.'\)[/:].\{-\}\ze\%(\.git\)\=$')
+  let base = substitute(base, 'github.com-[a-z]*', 'github.com', '')
   if index(domains, 'http://' . matchstr(base, '^[^:/]*')) >= 0
     return 'http://' . tr(base, ':', '/')
   elseif !empty(base)
```

It's not pretty but it works.

**Comment by tpope** [comment]
Porting https://github.com/tpope/vim-fugitive/blob/40d78f07dee2ffab68abb9d6d1a9e27843df0fe0/plugin/fugitive.vim#L2350-L2354 over should fix it.
