### ISSUE TITLE
Gbrowse returns: "'.' is not a supporte remote" for github enterprise

### ISSUE THREAD

**Issue by anapitupulu** [tpope/vim-rhubarb#25]
I am using a github enterprise and I already set `g:github_enterprise_urls` to be `['https://github.factset.com']` but everytime I run `:Gbrowse`, i got an error "'.' is not a supporte remote". Here is my `:Git remove -v`:

```
downstream	git@github.factset.com:anapitupulu/mobile-3.git (fetch)
downstream	git@github.factset.com:anapitupulu/mobile-3.git (push)
grane	git@gitlab.factset.com:grane/mobile-3.git (fetch)
grane	git@gitlab.factset.com:grane/mobile-3.git (push)
origin	https://github.factset.com/FactSet/mobile-3.git (fetch)
origin	https://github.factset.com/FactSet/mobile-3.git (push)
upstream	https://github.factset.com/FactSet/mobile-3.git (fetch)
upstream	https://github.factset.com/FactSet/mobile-3.git (push)
```

Any clue what could go wrong?

**Comment by tpope** [comment]
Make sure your current branch is tracking a branch on origin. In fact, try with `master` pointed at `origin/master` to rule out any bugs around branch handling.

**Comment by anapitupulu** [comment]
Hmm... it's still not working... So I ran:

```
:Git fetch origin
:Git checkout -B master origin/master
:Gbrowse // still failing
```

Is there any other command that I can use to debug the issue?

**Comment by tpope** [comment]
A few other things you can check:

* `:echo fugitive#repo().head()` (should be `master`)
* `:echo fugitve#repo().git_chomp('config', 'branch.master.remote')` (should be `origin`)
* `:echo fugitve#repo().git_chomp('config', 'branch.master.merge')` (should be `master`)

**Comment by anapitupulu** [comment]
So apparently, the last command `:echo fugitve#repo().git_chomp('config', 'branch.master.merge')` returns `refs/heads/master`... Could this be the issue?

**Comment by tpope** [comment]
My mistake, `refs/heads/master` is correct. The error message changing to reference `origin` is progress. Check `:echo fugitive#repo().git_chomp('remote', 'get-url', 'origin')`.

**Comment by tpope** [comment]
Oh, and you do have rhubarb.vim, correct?

**Comment by anapitupulu** [comment]
Arrrggghhhh, I am really stupid... Turn out I didn't have rhubarb.vim installed. I swear I though I have added it to my vim config file. Thanks for the help @tpope, much appreaciated!
