### ISSUE TITLE
Bad credentials

### ISSUE THREAD

**Issue by mikker** [tpope/vim-rhubarb#28]
Hi! I'm getting this error when trying to complete issue numbers:

```
Error detected while processing function rhubarb#omnifunc:
line   27:
rhubarb: Bad credentials
```

I have created an acces token, added it to my (otherwise empty) `.netrc`. The access token says "Never used" on GH fwiw. What can I do?

Thanks!

**Comment by tpope** [comment]
Unfortunately that only shows the line where the error was displayed. Try this instead:

```viml
echo rhubarb#repo_search('issues', 'state:open')
```

**Comment by mikker** [comment]
`{'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}`

`¯\_(ツ)_/¯`

**Comment by tpope** [comment]
Edit the autoload file, rename `s:curl_arguments` to `rhubarb#curl_arguments`, and check `:echo rhubarb#curl_arguments('/')`.

**Comment by mikker** [comment]
`['-q', '--silent', '-H', 'Accept: application/json', '-H', 'Content-Type: application/json', '-A', 'rhubarb.vim', '-u', 'mikker:!security find-generic-password -gs github.password -w | tr -d ''''', '/']`

**Comment by mikker** [comment]
```sh
$ security find-generic-password -gs github.password -w
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

**Comment by mikker** [comment]
https://github.com/mikker/dotfiles/blob/master/git/gitconfig.symlink#L13

**Comment by tpope** [comment]
What the heck is that? I've seen `github.password` before but never with a bang.

**Comment by mikker** [comment]
Tim, I have no idea where I got that from. But I removed it. And rhubarb works just fine now. Thanks for helping me debug the corner I'd painted myself into.
