### ISSUE TITLE
Error on `GBrowse` when using enterprise

### ISSUE THREAD

**Issue by pjrt** [tpope/vim-rhubarb#31]
When I call GBrowse in an Github Enterprise repo, I get the following error:

```
fugitive: No Gbrowse handler found for 'git@github.<company>.co:<project>/<repo>.git'
```

May be related to https://github.com/tpope/vim-rhubarb/issues/24, but not sure (the error is different). 

I've added this to my vimrc.

```
let g:github_enterprise_urls = ['https://github.<company>.co']
```

**Comment by tpope** [comment]
Do you have Rhubarb installed?

**Comment by pjrt** [comment]
@tpope you mean `vim-rrhubarb` (which I do have installed) or is there some other `rhubarb` I'm not aware of?

**Comment by tpope** [comment]
Yes, that. I misread this as being an issue on the Fugitive repo.

Check `:echo rhubarb#HomepageForUrl('git@github.<company>.co:<project>/<repo>.git')`.

**Comment by tpope** [comment]
It works fine for me with those literal values (i.e., leaving `<company>` untouched). Try the same.

**Comment by pjrt** [comment]
Even with those literal, it returns empty.

**Comment by tpope** [comment]
Try adding `return [domain_pattern, base]` after this line and see what it returns then:

https://github.com/tpope/vim-rhubarb/blob/b6cbbb0ad3e22870a3cd8d79a22722c63d98d18b/autoload/rhubarb.vim#L33

**Comment by pjrt** [comment]
Thanks for much for helping me out, btw.

Both using the real values and the verbatim values (ie:`<company>`) I get:
```
['github\.com', '']                                                                                            
```

**Comment by pjrt** [comment]
Interesting, so I added `domains` as well to the return statement, and it is coming out `[]`. Maybe my `g:github_enterprise_urls` isn't setup correctly?

**Comment by pjrt** [comment]
Yep, it seems that's the issue. Even though I have that setting set up in my vimrc, it seems to not be picked up (doing `echo g:github_enterprise_urls` yields an error about it not being set). 

So this is something with my environment. Thanks @tpope !

**Comment by pjrt** [comment]
Well this is odd. If I set that setting in my `~/.vimrc` it works, but if I set it in my `<local-project>/.vimrc` it doesn't.

Yet I have other settings in my local vimrc that are picked up just fine.

**Comment by pjrt** [comment]
Well I worked around it by making a `.vimrc-local` and just sourcing it from my github-visible vimrc. Though I find it very odd that that one setting wasn't available in `<local>/.vimrc`.

**Comment by pjrt** [comment]
nvm, I'm an idiot -_-

If anyone is wonder in the future, my issue was that I had an `.vimrc` AND an `.nvimrc` in my local project. And I use Neovim. I guess in some version of neovim this wasn't an issue and then it became an issue? Removing the `.vimrc` and moving everything into nvimrc fixed all issues.
