### ISSUE TITLE
What is the token inside .netrc for?

### ISSUE THREAD

**Issue by chris-fran** [tpope/vim-rhubarb#35]
I'm trying to make a setup that let me switch between both cloud and enterprise github. While testing some things, I realized if I don't set a `.netrc` at all, I can still do `:Gbrowse` and `:Git pull-request`.

I assume it's because I already have `hub` configured with an API token?

So what is the `.netrc` token for?

**Comment by tpope** [comment]
It's for issue omnicompletion.
