### ISSUE TITLE
Put the link after running :Gbrowse to clipboard

### ISSUE THREAD

**Issue by Migacz85** [tpope/vim-rhubarb#38]
This should be fairly easy but practicall too. After launching :Gbrowse it would be great if vim would trigger some function to put the current link in the clipboard for quickly passing it further.

**Comment by odnoletkov** [comment]
Check `:Gbrowse!`

**Comment by Migacz85** [comment]
Hm nothing happen when I run this command, do I need to configure it somehow on my linux system in order to work ? It will be simple as running `xsel -i' and the link string

**Comment by tpope** [comment]
It uses Vim's built-in clipboard support on the `+` register. If that isn't working for you, figure out why.

**Comment by andys8** [comment]
Exactly what I need. Can confirm `:GBrowse!` is working.

```
:[range]GBrowse! [args] Like :GBrowse, but put the URL on the clipboard rather
                        than opening it.
```


 Adding a small hint in the README would be cool: https://github.com/tpope/vim-fugitive/pull/2033
