### ISSUE TITLE
:Gbrowse doesn't work with private (non-Enterprise) repos

### ISSUE THREAD

**Issue by johnoshea** [tpope/vim-rhubarb#40]
:Gbrowse gives

`No Gbrowse handler found for 'https://<MY-USERNAME>@github.com/<MY-ORG-NAME>/<ORG-REPO>.git'`

for private repos (where the site url is github.com but the username isn't 'git'). I've set up a Personal Access Token in ~/.netrc but it looks like it's not getting that far - [this line](https://github.com/tpope/vim-rhubarb/blob/b6cbbb0ad3e22870a3cd8d79a22722c63d98d18b/autoload/rhubarb.vim#L33) is returning no match for `base`.

I've tried adding my GitHub username as follows, but it's giving the same result:

`let base = matchstr(a:url, '^\%(https\=://\|MY-USERNAME@\|git://\|git@\|ssh://git@\)\=\zs\('.domain_pattern.'\)[/:].\{-\}\ze\%(\.git\)\=$')`

...at which point I realize I have remarkably little idea of what I'm actually doing 😉

**Comment by tpope** [comment]
Try something like `^\%(https\=://\%([^@/:]*@\)\=\|git://...`.

**Comment by johnoshea** [comment]
That's worked - thank you!

**Comment by tpope** [comment]
Stick it in a PR and I'll merge.

**Comment by johnoshea** [comment]
Done - thanks again
