### ISSUE TITLE
Hub pull-request doesn't work via ! in neovim 

### ISSUE THREAD

**Issue by phantomwhale** [tpope/vim-rhubarb#47]
I've had problems using `!hub pull-request` and therefore this plugin (which I believe calls roughly that under the hood) with neovim

After looking around today, I believe the problem is neovim changed how `:!` works, and instead offers `:terminal` for similar behaviour.

When I try and execute `:Git pull-request` I see:

```
<whole bunch of what should be the PULLREQ page in vim>
^[[m^O^[[38;5;20m^[[48;5;19m.git/PULLREQ_EDITMSG [Git(code-of-conduct-agreement)]         1,1            All^[[1;6H^[[34h^[[?25hVim: Finished.
^[[23B^[[34h^[[?25h^[[?25l^[[2 q^[[?1002l^[[?1006l^[[m^O^[[34h^[[?25h^[[?1l^[>^[[?1049l^[[23;0;0t^[[?2004l^[[?1004l^[[34h^[[?25herror using text editor for pull request message

shell returned 1
```

When I run `:terminal hub pull-request` this seems to load the pull request edit screen correctly.

Other `:Git` commands seem to execute fine, but I think `hub pull-request`, because it invokes a new vim / neovim session, needs special treatment under neovim. E.g. https://github.com/neovim/neovim/wiki/FAQ#-and-system-do-weird-things-with-interactive-processes and https://github.com/neovim/neovim/issues/4287

Using Neovim 0.4.0-dev, and latest fugitive and rhubarb plugins (as of this date).

**Comment by tpope** [comment]
I'm not seeing an actionable solution. I don't wanna hack up Fugitive for a `hub` thing. If you like `:terminal hub pull-request` I say use that.

**Comment by phantomwhale** [comment]
Sure, and there may not be an actionable solution - there are a lot of moving parts to this is probably don't know enough about. And yeah, if the only reasonable action was to hack `fugitive` I'd 100% agree it's a non-starter

I put the issue here under the follow assumptions / understanding, at least one of which I'm sure is wrong:

(a) vim-rhubarb sets up using `hub` as the default `:Git` action, so it would be desirable that it offers support for the various `hub` actions if required

(b) the current setup would be broken for anyone using `neovim` due to how it changed `:!`. Mind you, given I'm the first to report any issue here between neovim and hub (either here, or via casual Google searching) I wonder if this statement is correct.

(c) I thought I saw some code in `fugitive` to handle the above inconsistency between vim and neovim, therefore thought putting a similar switch in vim-rhubarb would be consistent with that

Mind you, as nice and consistent as having ':Git pull-request` work in neovim would be, certainly running `:terminal hub pull-request` isn't much harder to remember and does indeed work nicely. 

Thanks for looking and replying (and for all the great plugins too, of course!)

**Comment by tpope** [comment]
It's not a guaranteed interface, but for now I added `:Git --paginate command` to force a terminal (since a pager necessitates a terminal).

**Comment by tpope** [comment]
https://github.com/tpope/vim-fugitive/pull/1433 should solve this once and for all.
