### ISSUE TITLE
Support for SSH Config and remote repos

### ISSUE THREAD

**Issue by alexluecke** [tpope/vim-rhubarb#48]
For my github repos I do not use my default ssh key, so for my ease I declare a host in my SSH config with something like:

```
Host github
    Hostname github.com
    User git
    IdentityFile ~/.ssh/name_of_key
```

So my remote in my git project looks like:

```
github:alexluecke/project
```

Unfortunately, fugitive looks for the actual github remote url. Is there a way to look for the SSH config?

**Comment by tpope** [comment]
Came across [an explanation of `core.sshCommand`](https://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use/912281#912281) today that sidesteps this issue and seems like a better approach all around. I am endorsing this as an official solution.
