### ISSUE TITLE
Running :Gbrowse without any file opens does open incorrect URL

### ISSUE THREAD

**Issue by KevinSjoberg** [tpope/vim-rhubarb#49]
Running `:Gbrowse` in the root of the project, without any files open (e.g., just netrw), opens an URL that 404.

It opens `https://github.com/username/repo/blob/branch` which is not valid. Switching `blob` to `tree` solves the problem. Running `:Gbrowse .` instead of `:Gbrowse` does also open the expected URL.

**Comment by tpope** [comment]
Needs a better error, but the answer is "don't do that". `:Gbrowse` browses to the current file, and you have no current file.

**Comment by KevinSjoberg** [comment]
@tpope I see. Yeah, a helpful error message would probably sort any confusion. Is `:Gbrowse .` working by accident and not a intended use case as well? Because it seems to work consistently.

**Comment by tpope** [comment]
`:Gbrowse .` is intentional. It browses to the current directory.
