### ISSUE TITLE
"Browse to upstream" support

### ISSUE THREAD

**Issue by NoahTheDuke** [tpope/vim-rhubarb#51]
Is it possible to add a way to browse to the equivalent file in the repo that I have set to `upstream` in my remotes? Maybe something like `:Gbrowse upstream`? My primary work is on a fork, and while it's good to keep it up to date, I only use the fork as a means of interacting with the "upstream" repo.

Either way, thanks so much, this is a time-saver.

**Comment by tpope** [comment]
`:Gbrowse @upstream`. It's documented under `:help :Gbrowse`.

**Comment by NoahTheDuke** [comment]
My apologies for missing thatt Thanks so much.
