### ISSUE TITLE
.netrc cannot access to environment variables

### ISSUE THREAD

**Issue by GopherJ** [tpope/vim-rhubarb#53]
Is it possible to write everything in `.vimrc` so that we can use environment variables, like `fugitive-gitlab.vim` and `vim-github-dashboard`

**Comment by tpope** [comment]
There is undocumented support for this.

https://github.com/tpope/vim-rhubarb/blob/5130596a65330a4e8523d3ac1582f6c31ea6bc63/autoload/rhubarb.vim#L67-L82
