### ISSUE TITLE
Please provide LICENSE/COPYRIGHT file

### ISSUE THREAD

**Issue by praiskup** [tpope/vim-rhubarb#55]
I know `:help license` is referenced, but still - for the re-packaging to
linux distributions - it is good idea to provide a copy of license file.

At least I, as Fedora packager, am sort of pushed to at least try to
request this:
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

**Comment by tpope** [comment]
Added. Been hesitant to rock the boat license-wise, since I have so many projects this could effect, but I guess Rhubarb can be a guinea pig.
