### ISSUE TITLE
Github enterprise won't work

### ISSUE THREAD

**Issue by mrassili** [tpope/vim-rhubarb#56]
Hi 👋 

I have installed `vim-rhubarb` and already had `fugitive`

when I run `:Gbrowse` in my personal github it works, but when I try it on GH enterprise repo it says:
`fugitive: No Gbrowse handler installed for 'git@github.<company>com:<project>/<repo>.git'`

(I did replace `<company>` 😉 )

running `:echo g:github_enterprise_urls` outputs `['https://github.<company>.com/']` ✅ 

running `:echo rhubarb#HomepageForUrl('git@github.com:mrassili/dotfiles.git')` outputs `https://github.com/mrassili/dotfiles` ✅ 

but running `:echo rhubarb#HomepageForUrl('git@github.<company>.com:<project>/<repo>.git')` outputs nothing (empty)

**Comment by tpope** [comment]
Remove the trailing slash.

**Comment by mrassili** [comment]
@tpope that was it. I knew it would be something so stupid 🤦‍♂ . Thank you!
unrelated: is there a way to specify the branch you wanna open the file in? it defaults to the current branch apparently
