### ISSUE TITLE
Gbrowse not opening the browser

### ISSUE THREAD

**Issue by ankit-jha** [tpope/vim-rhubarb#57]
I've been using Vim Fugitive plugin for some time now. Recently, I tried the Vim rhubarb plugin.
So for a github-repo it should work out of the box but **GBrowse** doesn't open the browser at all.
Although, **Gbrowse!** seems to work fine.

:messages gives me this output
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"osx_apps_install.sh" 114L, 2654C
https://github.com/username/commands/blob/master/osx_apps_install.sh
```

I believe it has to do with vim version.
I'm using apple compiled vim

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 9 2019 02:36:49)
Included patches: 1-503, 505-680, 682-1312

Appreciate any help on this.

**Comment by ankit-jha** [comment]
Tried to run **GBrowse** on an enterprise repo.

:messages gives me this output
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..78[18]..77[3]..<SNR>33_customOpenFile[1]..107[1]..123[3]..179[6]..180[17]..14:
line    3:
E325: ATTENTION
```

**Comment by tpope** [comment]
Open a new file, put a URL in it, and press `gx` on it. If that doesn't open the URL in a browser, the problem is with netrw.

**Comment by ankit-jha** [comment]
Yeah, you're right.
