### ISSUE TITLE
Auto-detect hub breaks :Gblame 

### ISSUE THREAD

**Issue by tiev** [tpope/vim-rhubarb#58]
Hi,

I have `:Gblame` do nothing and after inspection, I found out disabling these lines solves the issue

```vim
if get(g:, 'fugitive_git_command', 'git') ==# 'git' && executable('hub')
  let g:fugitive_git_command = 'hub'
endif
```

I'm running Ubuntu, neovim and using `hub`.

I think this smart feature is not necessary and should be left to users to configure.
Btw, I alias `hub` as `git` already.

**Comment by vieteh** [comment]
No error nor output.
It works when I disable rhubarb. Then drilling down I spot those lines

**Comment by vieteh** [comment]
Are you supporting hub-specific commands too?

**Comment by tiev** [comment]
Problem solved with this change https://github.com/tpope/vim-rhubarb/commit/857865bdab4bf134789484c36181346fdc29ccb9
