### ISSUE TITLE
[Question] Read the github issues from origin

### ISSUE THREAD

**Issue by rjshrjndrn** [tpope/vim-rhubarb#59]
Hi,
Thank you, as always for this wornderful plugin.

Have one question. 
Is it possible to configure the remote from which I need the GitHub issue autocomplete. 
- The issue is created in origin
- I'm working in my fork, with remote `mine`
- so in git commit `<c-x><c-o>` the issue populate from origin rather than `mine`

**Comment by tpope** [comment]
The default remote is the upstream: the value of `git config branch.<current-branch>.remote`. For your setup, I would recommend setting `branch.<current-branch>.remote` to `origin` and `branch.<current-branch>.pushRemote` to `mine`.

**Comment by rjshrjndrn** [comment]
Thank you for your reply @tpope. But I have got a bunch of repos like this. So is it possible to set a variable like `g:rhubarb_issue_remote` ?  Because I think most of the opensource contribution workflows like that.
