### ISSUE TITLE
Support special URL format for :Gbrowse

### ISSUE THREAD

**Issue by Asheq** [tpope/vim-rhubarb#60]
Can we support this format?:

```
git@github.com-{user}:{org}/{repo}.git
```

We just need to ignore the `-{user}` part and treat this as though it was

```
git@github.com:{org}/{repo}.git
```

## Some background on why I need this

I have multiple GitHub accounts that I use from the same computer (one for work and one personal). One [way to handle this](https://medium.com/better-programming/how-to-use-multiple-github-accounts-with-one-computer-c9ba3f851b75)  is to generate two ssh key pairs, one for each account, and configure ssh to use a particular key pair for a git repo based on how the URL looks. Please see that link above for more details.

That's why some of my git URLs have this form
```
git@github.com-{user}:{org}/{repo}.git
```

instead of

```
git@github.com:{org}/{repo}.git
```

But they both point to `github.com`.

**Comment by cod3g3nki** [comment]
My issue is quite similar. I've configured two VCS hosts on my computer, GitHub and Bitbucket, by generating two ssh key pairs. I've placed my configuration in `~/.ssh/config` and named VCS hosts as `gh` & `bb`. This makes my URIs look like `git@gh:{org}/{repo}.git` and `git@bb:{org}/{repo}.git`. Everything works fine in terminal but `:GBrowse` raises error:
```
fugitive: No Gbrowse handler installed for 'git@gh:cod3g3nki/nvim.git'
```

**Comment by cod3g3nki** [comment]
Ok, I've fixed my issue by changing host from `gh` to `github.com`. @Asheq it looks like configuring `~/.ssh/config` properly may fix your issue as well. This is how my configuration looks like right now:
```
#Github (default)
  Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa_gh

#Bitbucket (secondary)
  Host bb
  HostName bitbucket.org
  User git
  IdentityFile ~/.ssh/id_rsa_bb

#Others
  Host *
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes
```
Your `remote.origin.url` should also be set accordingly. In my case, I had to change it from `git@gh:{org}/{repo}.git` to `git@github.com:{org}/{repo}.git`. Therefore, setting one host to `github.com-{user}` and other to `github.com` might work for your case.

**Comment by tpope** [comment]
That will work to get Fugitive to recognize one account, but not the other. A possible solution for 2 accounts is to use SSH for one and HTTPS for the other. For more than that, you have to get creative: one possible solution is to set `core.sshCommand` locally on each repository to pass in the correct identity file.

But for better or worse, SSH host name aliases are the de facto solution to the problem, so I do think we should support in some capacity. The ssh config file is super easy to parse, so my ideal solution would be to parse it and figure out what host the user is actually connecting to automatically.

**Comment by tpope** [comment]
I accidentally implemented this.

**Comment by Asheq** [comment]
@tpope I don't think it works for git remote URLs specified in the form: `git@github.com-{user-name}:{org}/{repo}.git`

Is this right?

**Comment by tpope** [comment]
It works for `git@{literally-anything}:{org}/{repo}.git`, provided the appropriate SSH config is in place.
