### ISSUE TITLE
Incorrect url path for bitbucket

### ISSUE THREAD

**Issue by Artawower** [tpope/vim-rhubarb#61]
Hello, i have bitbucket private repo, when i trying :GBrowse i see next url:
`https://bitbucket.org/<company>/project/blob/develop/README.md`
but correct url is
`https://bitbucket.org/<company>/project/src/develop/README.md`

I also added next config:
```
let g:github_enterprise_urls = ['https://bitbucket.org/<company>']
```

When i use this plugin for my public repo on github everything is OK.

How can i fix that?

**Comment by tpope** [comment]
Rhubarb is for Github, not Bitbucket.
