### ISSUE TITLE
Using alongside NVim Compe

### ISSUE THREAD

**Issue by harrysolovay** [tpope/vim-rhubarb#66]
I was wondering if you had advice for getting username/issue ID/etc. autocompletions working alongside [compe](https://github.com/hrsh7th/nvim-compe)? Would it be possible to keep Compe enabled (for its from-buffer autocompletion), while still getting the completion of Rhubarb? Or do I need to choose one / override the omnifunc for the `gitcommit` file type? 

Any suggestions would be greatly appreciated. Thank you!

**Comment by tpope** [comment]
I can't speak to compe specifically, but if you can't use `'omnifunc'`, you could instead use `'completefunc'`, which is the same thing but on `CTRL-X CTRL-U`.  Try something like this:

```vim
augroup my_rhubarb
  autocmd!
  if exists('+completefunc')
    autocmd FileType gitcommit
          \ if !empty(rhubarb#HomepageForUrl(FugitiveRemoteUrl()))
          \   setlocal completefunc=rhubarb#Complete
          \ endif
  endif
augroup END
```

**Comment by harrysolovay** [comment]
Got it working. Thank you @tpope!
