### ISSUE TITLE
Regression: regex for github_enterprise_urls stopped working

### ISSUE THREAD

**Issue by paulodiovani** [tpope/vim-rhubarb#67]
I used to have a RE to support Github enterprise URLs as follows.
This allowed me to use `:GBrowse` command with (almost) any GitHub enterprise.

```vim
let g:github_enterprise_urls = ['[-_\.a-zA-Z0-9]\+']
```

But after a recent update, it stopped working and I must explicitly add the domains.

Use a RE for enterprise urls are preferred because:

- shorter configuration that allows most domains
- config can be shared among users who doesn't necessarily work on the same GitHub enterprise

**Comment by tpope** [comment]
> Use a RE for enterprise urls are preferred because:
> 
> * shorter configuration that allows most domains

Including domains like `gitlab.com` and `bitbucket.org`. This prevents every other third party adapter from working.

> * config can be shared among users who doesn't necessarily work on the same GitHub enterprise

The fact you can break things not only for yourself but also other people is not an argument that works in your favor.

There is, however, an `autodetect-enterprise` branch you might find interesting.

**Comment by paulodiovani** [comment]
> > Use a RE for enterprise urls are preferred because:
> > 
> > * shorter configuration that allows most domains
> 
> Including domains like `gitlab.com` and `bitbucket.org`. This prevents every other third party adapter from working.

For information,
It always worked for me before with `gitlab.com`, without need for another plugin.

> > * config can be shared among users who doesn't necessarily work on the same GitHub enterprise
> 
> The fact you can break things not only for yourself but also other people is not an argument that works in your favor.

Shared configuration is very common,
most of mine are based on other people.

> There is, however, an `autodetect-enterprise` branch you might find interesting.

I'll take a look, thanks.
