### ISSUE TITLE
Don't open browser when over ssh

### ISSUE THREAD

**Issue by TamaMcGlinn** [tpope/vim-rhubarb#69]
I run neovim over `ssh -Y host` so that copy-pasting works. I use vim-rhubarb in various contexts, which works because it helpfully also prints the url it is opening, so after triggering GBrowse there is a link I can cntrl-click in the terminal to open that link in my browser on the local machine.

However, because I am over ssh -Y, it also opens a really really slow browser over ssh, and it takes a long time for it to open far enough that I can click the X to close that window.

Any ideas how vim-rhubarb could maybe detect that it is over ssh, and not open the browser at all? Or should there just be an option added to not open the browser? I could set that in my vimrc after checking the machine name, for instance.

**Comment by tpope** [comment]
If you don't want to open the browser, use `:GBrowse!`. You can also change the behavior of `:GBrowse` by redefining `:Browse` to do whatever the heck you want:

```vim
if exists('$SSH_CONNECTION')
  command! -bar -nargs=* Browse echo "Hey, we're on ssh, so you'll have to open this by hand: " . <q-args>
endif
```
