### ISSUE TITLE
GBrowse does not open on WSL

### ISSUE THREAD

**Issue by benmaia** [tpope/vim-rhubarb#74]
Hey!

I'm using WSL and when I use the command GBrowse it prints the URL in the command line but it doesn't open any browser, is there some special config I have to make? I know I can open URL from WSL because I have other plug-ins like Markdown Preview.

Thank you for your time!

**Comment by tpope** [comment]
It uses the backend of the `gx` map provided by netrw (included with Vim). Try typing a URL and pressing gx on it. If that doesn't open it in a browser, see `:help netrw-gx` for configuring it.

**Comment by lucsmachado** [comment]
For future reference in case anyone stumbles upon this issue, here's what you need to do for `:GBrowse` to work in WSL, as per [this answer](https://superuser.com/a/1317266):
- Vim:
`let g:netrw_browsex_viewer="cmd.exe /C start"`
- Neovim
`vim.g.netrw_browsex_viewer = 'cmd.exe /C start'`
