### ISSUE TITLE
Support for reading Host alias from ssh_config.d directory

### ISSUE THREAD

**Issue by FriendlyTroll** [tpope/vim-rhubarb#79]
Hi,

first thanks a lot for an amazing plugin.

This issue is related to [this closed issue](https://github.com/tpope/vim-rhubarb/issues/60) about reading github alias hosts from ssh config file. If you have a custom Host that you are using e.g. github-work and this is set in .ssh/config file it works fine.

```
Host github-work
  Hostname github.com
  IdentityFile ~/.ssh/sshkey-github
```
However I have some host configs split in different files and those are then included in .ssh/config like so
```

Include ~/.ssh/ssh_config.d/work.conf

Include ~/.ssh/ssh_config.d/private.conf
```
If the above host alias is located in any of the files in ~/.ssh/ssh_config.d you will get the error

  fugitive: No Gbrowse handler installed for ...

**Comment by tpope** [comment]
This should have been fixed by https://github.com/tpope/vim-fugitive/commit/ec8f7eed103c6d5b75eac69196bb87db0825629a. Let me know if it still doesn't work.

**Comment by amaretic-mbb** [comment]
Sorry still doesn't work for me. I have the latest master installed via vim-plug. I double checked by going to the _.vim/plugged/vim-fugitive_ dir and doing ```git show ec8f7ee``` which returns the commit you linked to.

**Comment by FriendlyTroll** [comment]
Sorry still doesn't work for me. I have the latest master installed via vim-plug. I double checked by going to the ._vim/plugged/vim-fugitive_ dir and doing `git show ec8f7ee` which returns the commit you linked to.

**Comment by tpope** [comment]
Can you test if it works if you use relative paths?

```
Include ssh_config.d/work.conf

Include ssh_config.d/private.conf
```

**Comment by FriendlyTroll** [comment]
Yep seems to work with relative paths. Thank you!

**Comment by tpope** [comment]
I was unaware that `~` was supported in includes. I've added support in Fugitive.
