### ISSUE TITLE
equivalent plugin or capability to extend to gitlab?

### ISSUE THREAD

**Issue by mmerickel** [tpope/vim-rhubarb#80]
Is there a plugin like vim-rhubarb specifically for gitlab? Or even better, just a way to use rhubarb with gitlab urls? I haven't tried the omnicomplete features but I'll point out for anyone who's curious that `let g:github_enterprise_urls = ['https://gitlab.com']` actually works for `:GBrowse` for me. It also works for a self-hosted instance URL.

From the README I get the impression that the other stuff will fail where rhubarb is actually trying to hit the API.

For `:GBrowse` I'm interested in a plugin that does a standard git-to-https translate for gitlab/github/etc without the extra API features. Is anyone aware of something? ArgoCD supports a function to do this that I'm thinking of as inspiration https://github.com/argoproj/argo-cd/blob/aaabb050b24751182fc8685385f10d2047be1717/util/notification/expression/repo/repo.go#L80-L88

Thanks!

**Comment by tpope** [comment]
https://github.com/shumphrey/fugitive-gitlab.vim is intended to essentially be Rhubarb for GitLab.

**Comment by mmerickel** [comment]
Thank you for the pointer!
